### PR TITLE
polyfill usage

### PR DESCRIPTION
**Pull request by LinusU**
See discussion in #1

### CODE REVIEW

**Comment by LinusU** [comment]
@fengmk2 Mind merging this?

The build fails because it can't install Node.js 0.4. I think that the correct path here is just to drop 0.4 since it's extremely old and I don't think anyone is using it anymore. Maybe target `0.10`, `0.12` and `iojs`?

**Comment by LinusU** [comment]
ping @fengmk2

**Comment by fengmk2** [comment]
+1

I will release major version

**Comment by LinusU** [comment]
:tada:

**Pull request merged**
